sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g gulp
  - npm i -g snyk
  - npm i -g codecov
before_script:
  - if (( "${TRAVIS_NODE_VERSION}" >= 6 )) && [ "$TRAVIS_BRANCH" = "master" ]; then export COVERAGE_REPORT=true; fi;
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - gulp stats
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
